INSERT INTO Players (Name) VALUES ('John Doe');
INSERT INTO Players (Name) VALUES ('Jane Smith');
INSERT INTO Players (Name) VALUES ('Tom Hanks');
INSERT INTO Players (Name) VALUES ('Emily Davis');
INSERT INTO Players (Name) VALUES ('Michael Johnson');
INSERT INTO Players (Name) VALUES ('Chris Lee');
INSERT INTO Players (Name) VALUES ('Sarah Williams');
INSERT INTO Players (Name) VALUES ('David Brown');
INSERT INTO Players (Name) VALUES ('Olivia Jones');
INSERT INTO Players (Name) VALUES ('James White');
INSERT INTO Players (Name) VALUES ('Lucas Green');
INSERT INTO Players (Name) VALUES ('Sophia Turner');
INSERT INTO Players (Name) VALUES ('Liam Miller');
INSERT INTO Players (Name) VALUES ('Charlotte Clark');
INSERT INTO Players (Name) VALUES ('Amelia Rodriguez');
INSERT INTO Players (Name) VALUES ('Ethan Lewis');
INSERT INTO Players (Name) VALUES ('Ava Martinez');
INSERT INTO Players (Name) VALUES ('Mason Scott');
INSERT INTO Players (Name) VALUES ('Isabella Allen');

INSERT INTO Matches (Player1, Player2, Winner) VALUES (1, 2, 1);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 4, 3);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (5, 6, 5);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (7, 8, 7);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (9, 10, 9);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 4, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (6, 8, 8);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 5, 5);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (1, 7, 1);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (10, 2, 10);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (11, 12, 11);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (13, 14, 13);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (15, 16, 15);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (17, 18, 17);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (19, 20, 19);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (13, 15, 13);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (14, 16, 16);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (11, 17, 17);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (12, 18, 18);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (19, 1, 19);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (2, 14, 2);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (3, 17, 17);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (5, 18, 18);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (6, 19, 6);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (7, 20, 7);
INSERT INTO Matches (Player1, Player2, Winner) VALUES (10, 12, 12);